services:
  core-service:
    build: ./core-service
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: sqlite:////data/db.sqlite3
    volumes:
      - core_data:/data
    ports:
      - "8001:8001"
    command: >
      sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8001"

  media-service:
    build: ./media-service
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: sqlite:////data/db.sqlite3
    volumes:
      - media_data:/data
    ports:
      - "8002:8002"
    command: >
      sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8002"

volumes:
  core_data:
  media_data:
